version: 1
update_configs:
    - package_manager: "java:gradle"
      directory: "./demo-java/"
      update_schedule: "daily"

    - package_manager: "java:gradle"
      directory: "./demo-kotlin/"
      update_schedule: "daily"

    - package_manager: "java:gradle"
      directory: "./compat/"
      update_schedule: "daily"
